### ISSUE TITLE
Problems with the implementation

### ISSUE THREAD

**Issue by johnwcowan** [scheme-requests-for-implementation/srfi-121#1]
Hi,

I'm looking into reference implementation and have noticed that
there are signature mismatches. I'm listing ones I've found below:

- gconcatenate
   The SRFI says this takes one argument of Generator generator but
   the reference implementation takes arbitrary length arguments.

- gmerge, gunion, gintersection, gmap
   The SRFI says this requires at least 2 arguments but the reference
   implementation requires only one (comparator).

- gfold
   The SRFI says this requires at least 3 arguments but the reference
   implementation requires only two (comparator and seed).

- gfilter-map
   The SRFI says this requires at least 2 arguments but the reference
   implementation requires only one (proc).

Cheers,

--
_/_/
Takashi Kato

**Comment by arthurgleckler** [comment]
Please send these comments to srfi-121@srfi.schemers.org so that everyone will see them.

Thank you.
