### ISSUE TITLE
Should gdelete-neighbor-dups take a comparator?

### ISSUE THREAD

**Issue by johnwcowan** [scheme-requests-for-implementation/srfi-121#2]
And gdelete-neighbor-dups takes procedure as its optional argument but
other procedures such as gmerge or gunion takes comparator. Should it
be a comparator for consistency? (Though it's also mentioned in the
comment.) Or others should accept procedures instead of comparators?

Takashi Kato

**Comment by arthurgleckler** [comment]
Please send these comments to srfi-121@srfi.schemers.org so that everyone will see them.
